# Terrain & sky
SKY_TILE = '0'
BREAKABLE_BRICK = '1'
MYSTERY_BOX = '2'
EMPTY_BOX = '5'
BRICK_TERRAIN = '345'
MUSHROOM_TERRAIN = '116'
END_OF_GAME = '1014'

# Link 
PLAYER_TILE = '-1'

# Collectibles
COIN = '39'
EXTRA_LIFE = '194'
FIRE_MARIO = '1944'
PAC_MAN = '1714'

# NPCs
BOKOBLIN = '240'
GHOST = '294'
DONKEY_KONG = '241'
GANONDORF = '242'

# Collections
BACKDROP_TILES = [SKY_TILE, '397', '398', '399']
MONSTERS = [BOKOBLIN, GHOST, DONKEY_KONG, GANONDORF]
BREAKABLE = [BREAKABLE_BRICK]
